package com.example.ui.screens.toolbox

import com.example.R

/**
 * 100 种鸟类叫声科普库（纯本地离线，音频资源 res/raw/bird_XXX.ogg 与资源名一一对应）
 * 由脚本生成：中文名 / 学名 / 分类 / 科普简介
 */
object BirdLibrary {
    data class Bird(
        val id: Int,
        val name: String,
        val sciName: String,
        val category: String,
        val desc: String,
        val rawRes: Int
    )

    val birds: List<Bird> = listOf(
        Bird(1, "麻雀", "Passer montanus", "雀形目", "城市乡村最常见的小鸟，群居叽叽喳喳，冬天会挤在一起取暖。", R.raw.bird_001),
        Bird(2, "喜鹊", "Pica pica", "雀形目", "吉祥鸟，黑白配色拖着长尾巴，会''喳喳''叫，聪明记性好。", R.raw.bird_002),
        Bird(3, "大嘴乌鸦", "Corvus macrorhynchos", "雀形目", "全身黑色，叫声沙哑''呱呱''，非常聪明，会使用工具。", R.raw.bird_003),
        Bird(4, "家燕", "Hirundo rustica", "雀形目", "春来秋去，剪刀尾，低飞捉虫预报天气，叫声细碎轻快。", R.raw.bird_004),
        Bird(5, "大杜鹃", "Cuculus canorus", "鹃形目", "就是''布谷鸟''，叫声''布谷布谷''两声调，自己不孵蛋。", R.raw.bird_005),
        Bird(6, "新疆歌鸲", "Luscinia megarhynchos", "雀形目", "夜莺，深夜鸣唱婉转悠扬，被誉为''歌唱家''。", R.raw.bird_006),
        Bird(7, "画眉", "Garrulax canorus", "雀形目", "眼周白纹如画眉，鸣声多变洪亮，常被养作观赏鸟。", R.raw.bird_007),
        Bird(8, "蒙古百灵", "Melanocorypha mongolica", "雀形目", "草原歌星，边飞边唱，叫声优美持久，百灵鸟之一。", R.raw.bird_008),
        Bird(9, "黑枕黄鹂", "Oriolus chinensis", "雀形目", "金黄羽毛配黑枕，鸣声圆润悠扬，古人诗中的''黄鹂''。", R.raw.bird_009),
        Bird(10, "云雀", "Alauda arvensis", "雀形目", "冲天直飞边唱边升，叫声清脆流畅，''云雀高歌''。", R.raw.bird_010),
        Bird(11, "白头鹎", "Pycnonotus sinensis", "雀形目", "头后一撮白毛，叫声婉转顽皮，城市公园常见。", R.raw.bird_011),
        Bird(12, "珠颈斑鸠", "Spilopelia chinensis", "鸽形目", "颈上珍珠点花纹，叫声低沉''咕咕咕''三连音。", R.raw.bird_012),
        Bird(13, "大斑啄木鸟", "Dendrocopos major", "䴕形目", "森林医生，笃笃笃啄木捉虫，叫声短促''唧''。", R.raw.bird_013),
        Bird(14, "长耳鸮", "Asio otus", "鸮形目", "猫头鹰，大眼圆脸有耳羽，夜里''呼呼''低鸣。", R.raw.bird_014),
        Bird(15, "苍鹰", "Accipiter gentilis", "鹰形目", "猛禽盘旋高飞，叫声尖锐''克诶''，捕猎一击必中。", R.raw.bird_015),
        Bird(16, "海鸥", "Larus canus", "鸻形目", "海边码头常见，白色海鸟，叫声''嘎嘎''像笑声。", R.raw.bird_016),
        Bird(17, "小白鹭", "Egretta garzetta", "鹈形目", "雪白羽毛黄嘴黑腿，涉水觅食，叫声低沉''嘎''。", R.raw.bird_017),
        Bird(18, "丹顶鹤", "Grus japonensis", "鹤形目", "吉祥长寿象征，丹顶红冠，叫声高亢嘹亮传数里。", R.raw.bird_018),
        Bird(19, "蓝孔雀", "Pavo cristatus", "鸡形目", "开屏华丽如画，叫声凄厉''嗷嗷''，十分特殊。", R.raw.bird_019),
        Bird(20, "虎皮鹦鹉", "Melopsittacus undulatus", "鹦形目", "会学人说话的小鹦鹉，叫声细碎欢快，活泼好动。", R.raw.bird_020),
        Bird(21, "原鸽", "Columba livia", "鸽形目", "家鸽野鸽祖先，低声''咕咕''，爱吃谷物。", R.raw.bird_021),
        Bird(22, "原鸡", "Gallus gallus", "鸡形目", "家鸡祖先，雄鸡'喔喔喔'打鸣，天亮就报晓。", R.raw.bird_022),
        Bird(23, "家鸭", "Anas platyrhynchos domesticus", "雁形目", "''嘎嘎嘎''叫个不停，走路摇摇摆摆，不怕水。", R.raw.bird_023),
        Bird(24, "绿头鸭", "Anas platyrhynchos", "雁形目", "野鸭，头和颈绿色闪光，叫声响亮''嘎嘎''。", R.raw.bird_024),
        Bird(25, "家鹅", "Anser anser domesticus", "雁形目", "看家护院的高手，大嗓门''昂昂''叫，敢追赶生人。", R.raw.bird_025),
        Bird(26, "大天鹅", "Cygnus cygnus", "雁形目", "优雅白衣天使，叫声低沉悠远，冬季来越冬。", R.raw.bird_026),
        Bird(27, "黄雀", "Spinus spinus", "雀形目", "小个子黄绿相间，鸣声婉转多变，公鸟更爱唱。", R.raw.bird_027),
        Bird(28, "金丝雀", "Serinus canaria", "雀形目", "笼养名鸟，羽色金黄，鸣声悦耳持久，甚至会''学曲''。", R.raw.bird_028),
        Bird(29, "八哥", "Acridotheres cristatellus", "雀形目", "头顶一撮羽冠，会模仿人语鸟叫，学说话高手。", R.raw.bird_029),
        Bird(30, "鹩哥", "Gracula religiosa", "雀形目", "说话能力最强学舌鸟，叫声多变又会模仿。", R.raw.bird_030),
        Bird(31, "普通翠鸟", "Alcedo atthis", "佛法僧目", "蓝绿羽毛如宝石，盯着水面俯冲抓鱼，吱吱叫。", R.raw.bird_031),
        Bird(32, "戴胜", "Upupa epops", "犀鸟目", "头顶扇状羽冠，臭咕咕，叫声'咕咕咕'三连，喜欢草丛翻虫。", R.raw.bird_032),
        Bird(33, "蜂鸟", "Trochilidae", "雨燕目", "世界上最小的鸟，翅膀扇动嗡嗡响，倒飞吸花蜜。", R.raw.bird_033),
        Bird(34, "白鹤", "Leucogeranus leucogeranus", "鹤形目", "白头白羽红脸颊，全球珍稀，叫声清亮。", R.raw.bird_034),
        Bird(35, "灰鹤", "Grus grus", "鹤形目", "灰毛头顶红，迁徙列队飞行，叫声悠远。", R.raw.bird_035),
        Bird(36, "黑天鹅", "Cygnus atratus", "雁形目", "全身黑配红嘴，优雅低鸣，原产澳大利亚。", R.raw.bird_036),
        Bird(37, "朱鹮", "Nipponia nippon", "鹈形目", "东方宝石，羽毛白里透红，叫声低哑。", R.raw.bird_037),
        Bird(38, "乌鸫", "Turdus merula", "雀形目", "全黑黄嘴，叫声音韵丰富，清晨啼鸣婉转，''百舌鸟''。", R.raw.bird_038),
        Bird(39, "红嘴蓝鹊", "Urocissa erythroryncha", "雀形目", "蓝色长尾漂亮鸟，叫声粗哑多变，机警大胆。", R.raw.bird_039),
        Bird(40, "红腹锦鸡", "Chrysolophus pictus", "鸡形目", "金鸡，五彩羽毛华丽，叫声短促''咯''。", R.raw.bird_040),
        Bird(41, "白鹇", "Lophura nycthemera", "鸡形目", "白羽长尾如仙鸟，叫声低沉嘶哑。", R.raw.bird_041),
        Bird(42, "普通鸬鹚", "Phalacrocorax carbo", "鲣鸟目", "鱼鹰，黑羽绿眼，站在竹筏上抓鱼，叫声沙哑。", R.raw.bird_042),
        Bird(43, "苍鹭", "Ardea cinerea", "鹈形目", "老等，站在水边不动等鱼，叫声粗哑''嘎''。", R.raw.bird_043),
        Bird(44, "豆雁", "Anser fabalis", "雁形目", "人字形大雁，秋去春来，叫声响亮''鹅''。", R.raw.bird_044),
        Bird(45, "白尾海雕", "Haliaeetus albicilla", "鹰形目", "猛禽之王，翼展两米，叫声尖细嘹亮。", R.raw.bird_045),
        Bird(46, "游隼", "Falco peregrinus", "隼形目", "飞行速度最快的鸟，俯冲时速300km，叫声尖锐。", R.raw.bird_046),
        Bird(47, "红隼", "Falco tinnunculus", "隼形目", "悬停捕鼠小猛禽，叫声尖细''唧唧''。", R.raw.bird_047),
        Bird(48, "角百灵", "Eremophila alpestris", "雀形目", "头上有小角羽冠，高原草地鸣唱。", R.raw.bird_048),
        Bird(49, "大山雀", "Parus major", "雀形目", "黑头白脸颊，叫声''吱吱-黑''像打铁声，爱捉虫。", R.raw.bird_049),
        Bird(50, "沼泽山雀", "Poecile palustris", "雀形目", "黑顶白颊山雀，叫声滴滴答答轻快。", R.raw.bird_050),
        Bird(51, "煤山雀", "Periparus ater", "雀形目", "头顶黑冠，叫声细碎''吱吱''，常低头找虫。", R.raw.bird_051),
        Bird(52, "银喉长尾山雀", "Aegithalos glaucogularis", "雀形目", "小胖球拖着长尾，叫声弹舌般轻快，成群活动。", R.raw.bird_052),
        Bird(53, "红头长尾山雀", "Aegithalos concinnus", "雀形目", "红头黑眼罩，萌萌的小团子，叫声细碎。", R.raw.bird_053),
        Bird(54, "黄腹山雀", "Pardaliparus venustulus", "雀形目", "黄肚子小雀，叫声带金属感''叮叮''。", R.raw.bird_054),
        Bird(55, "太平鸟", "Bombycilla garrulus", "雀形目", "头戴羽冠，翅膀红斑如蜡，叫声细碎。", R.raw.bird_055),
        Bird(56, "北红尾鸲", "Phoenicurus auroreus", "雀形目", "橙红尾巴，点头翘尾，叫声婉转。", R.raw.bird_056),
        Bird(57, "白鹡鸰", "Motacilla alba", "雀形目", "黑白相间，边走边翘尾巴，叫声''唧铃铃''。", R.raw.bird_057),
        Bird(58, "灰头麦鸡", "Vanellus cinereus", "鸻形目", "黑嘴黄腿，水田草地''嘀嘀''叫，护巢时俯冲驱赶。", R.raw.bird_058),
        Bird(59, "黑水鸡", "Gallinula chloropus", "鹤形目", "黑羽红额头，脚大像鸡，''咕咕''潜行芦苇丛。", R.raw.bird_059),
        Bird(60, "白骨顶", "Fulica atra", "鹤形目", "头顶白色骨板，双着黑羽，叫声响亮''咔'。", R.raw.bird_060),
        Bird(61, "斑嘴鸭", "Anas zonorhyncha", "雁形目", "黄嘴尖带黑斑，叫声''嘎嘎''随和。", R.raw.bird_061),
        Bird(62, "赤麻鸭", "Tadorna ferruginea", "雁形目", "橙棕色大鸭，叫声嘶哑''啊-啊''，常成对活动。", R.raw.bird_062),
        Bird(63, "鸳鸯", "Aix galericulata", "雁形目", "爱情鸟，雄鸟羽毛华丽多彩，叫声纤细。", R.raw.bird_063),
        Bird(64, "白胸翡翠", "Halcyon smyrnensis", "佛法僧目", "绿瓦蓝背棕头，叫声尖锐''嘀''，捉虫好手。", R.raw.bird_064),
        Bird(65, "蓝翡翠", "Halcyon pileata", "佛法僧目", "蓝紫色大翠鸟，叫声''克li''，岸边树枝等鱼。", R.raw.bird_065),
        Bird(66, "斑文鸟", "Lonchura punctulata", "雀形目", "栗色小雀带鳞斑，成群''吱吱''，住稻田村庄。", R.raw.bird_066),
        Bird(67, "白腰文鸟", "Lonchura striata", "雀形目", "背上白斑，算命先生养的''叼签鸟''，叫声碎。", R.raw.bird_067),
        Bird(68, "黑尾蜡嘴雀", "Eophona migratoria", "雀形目", "黄嘴粗壮，叫声响亮''guei''，爱吃种子硬壳。", R.raw.bird_068),
        Bird(69, "锡嘴雀", "Coccothraustes coccothraustes", "雀形目", "嘴巴像钳子，能夹开樱桃核，叫声清脆。", R.raw.bird_069),
        Bird(70, "金翅雀", "Chloris sinica", "雀形目", "翅膀金黄，叫声''叮铃铃''金属感，成群飞。", R.raw.bird_070),
        Bird(71, "朱顶雀", "Acanthis flammea", "雀形目", "头顶朱红，北极来的冬候鸟，叫声细碎。", R.raw.bird_071),
        Bird(72, "燕雀", "Fringilla montifringilla", "雀形目", "栗色肩红腹，北国来客，叫声明亮。", R.raw.bird_072),
        Bird(73, "普通朱雀", "Carpodacus erythrinus", "雀形目", "雄鸟胭脂红，叫声婉转抒情''do re mi''。", R.raw.bird_073),
        Bird(74, "松鸦", "Garrulus glandarius", "雀形目", "从林蓝翼斑，爱藏橡子，叫声粗哑多变。", R.raw.bird_074),
        Bird(75, "灰喜鹊", "Cyanopica cyanus", "雀形目", "蓝翅长尾，群居''嘎呀''叫，护林小卫士。", R.raw.bird_075),
        Bird(76, "蓝山雀", "Cyanistes caeruleus", "雀形目", "蓝冠黄腹，叫声脆亮''咝咝''。", R.raw.bird_076),
        Bird(77, "戴菊", "Regulus regulus", "雀形目", "最小的鸟之一，头顶金黄冠纹，叫声细如蚊。", R.raw.bird_077),
        Bird(78, "鹪鹩", "Troglodytes troglodytes", "雀形目", "棕褐小圆球，尾巴翘起，叫声洪亮出人意料。", R.raw.bird_078),
        Bird(79, "棕头鸦雀", "Sinosuthora webbiana", "雀形目", "黄檀小团子，''唧唧''叫着穿梭芦苇，成群。", R.raw.bird_079),
        Bird(80, "震旦鸦雀", "Paradoxornis heudei", "雀形目", "中国特有，芦苇丛里''咚咚''啄虫，濒危保护鸟。", R.raw.bird_080),
        Bird(81, "中华攀雀", "Remiz consobrinus", "雀形目", "织毛衣高手，巢挂在柳枝上，叫声细尖。", R.raw.bird_081),
        Bird(82, "黑卷尾", "Dicrurus macrocercus", "雀形目", "黑羽叉尾，叫声尖锐机警，护巢追打猛禽。", R.raw.bird_082),
        Bird(83, "发冠卷尾", "Dicrurus hottentottus", "雀形目", "头上有细长冠羽，叫声模仿力强，音调多变。", R.raw.bird_083),
        Bird(84, "红耳鹎", "Pycnonotus jocosus", "雀形目", "头顶高冠脸颊红，叫声''皮皮''活泼，南方常见。", R.raw.bird_084),
        Bird(85, "黄臀鹎", "Pycnonotus xanthorrhous", "雀形目", "白褐身黄屁股，叫声明快，果园树林活跃。", R.raw.bird_085),
        Bird(86, "领雀嘴鹎", "Spizixos semitorques", "雀形目", "绿黄配色领上白圈，叫声清脆''quik''。", R.raw.bird_086),
        Bird(87, "白胸苦恶鸟", "Amaurornis phoenicurus", "鹤形目", "叫声''苦恶-苦恶''，黑夜乱叫，白胸黑背。", R.raw.bird_087),
        Bird(88, "董鸡", "Gallicrex cinerea", "鹤形目", "雄鸡头上有红角，叫声拖长''董、董''，夜间池塘鸣。", R.raw.bird_088),
        Bird(89, "普通秧鸡", "Rallus aquaticus", "鹤形目", "芦苇丛隐士，叫声''吱咯吱''，见人就钻。", R.raw.bird_089),
        Bird(90, "丘鹬", "Scolopax rusticola", "鸻形目", "森林夜行鸟，嘴长腿短，觅食时''扭屁股''。", R.raw.bird_090),
        Bird(91, "扇尾沙锥", "Gallinago gallinago", "鸻形目", "飞行时尾羽振动''嗡嗡''响，叫声尖锐。", R.raw.bird_091),
        Bird(92, "矶鹬", "Actitis hypoleucos", "鸻形目", "最爱点头晃尾巴，叫声''呲呲''沿水岸跑。", R.raw.bird_092),
        Bird(93, "白额雁", "Anser albifrons", "雁形目", "额头白斑，成群结队''咔咔''叫，南来北往。", R.raw.bird_093),
        Bird(94, "小天鹅", "Cygnus columbianus", "雁形目", "比大天鹅小，嘴基黄斑，叫声清亮悠远。", R.raw.bird_094),
        Bird(95, "白琵鹭", "Platalea leucorodia", "鹈形目", "铲子上嘴，左右扫水捉鱼，叫声低沉。", R.raw.bird_095),
        Bird(96, "黑脸琵鹭", "Platalea minor", "鹈形目", "全球濒危明星，扁平黑嘴，Eastern宝石。", R.raw.bird_096),
        Bird(97, "卷羽鹈鹕", "Pelecanus crispus", "鹈形目", "大嘴巴兜鱼，灰白大鸟，叫声低沉沙哑。", R.raw.bird_097),
        Bird(98, "灰斑鸠", "Streptopelia decaocto", "鸽形目", "形似珠颈斑鸠但无珍珠斑，叫声低沉舒缓的三连音。", R.raw.bird_098),
        Bird(99, "小鸊鹈", "Tachybaptus ruficollis", "鸊鹈目", "小水鸟会潜水，叫声一连串笑颤音，非常特别。", R.raw.bird_099),
        Bird(100, "斑鸠草雀", "Taeniopygia guttata", "雀形目", "袖珍鸟有橙色腮帮，叫声滋滋震音，很受欢迎。", R.raw.bird_100),
    )
}